version: '3'

services:
  database:
    image: 'postgres:14'
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postresql # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: default_database